#include "OS2_RT_MENU.h"

#include "../RT_ACCELTABLE/RT_ACCELTABLE.h"
#include "../RT_STRING/RT_STRING.h"

#include <stdexcept>

namespace peare {
namespace resources {
namespace {

// The RT_MENU in OS/2 is very different from the equivalent for Windows.
// Special thanks to EDM2.com for providing how this resource is structured.
// The format is described at "when rt = 3" (search for it in the page)
// https://www.edm2.com/index.php/Resources_and_Decompiling_Them
// This class has been almost completely generated by Google Gemini after providing the described format and structure.

// Constants for Menu Item Styles (MIS_*) - These are illustrative, actual values might vary slightly
// These values are common in Windows resource definitions.
constexpr quint16 MIS_STRING    = 0x0000; // Default for a simple string menu item
constexpr quint16 MIS_SUBMENU   = 0x0010; // Indicates a submenu (POPUP)
constexpr quint16 MIS_SEPARATOR = 0x0800; // Separator line
constexpr quint16 MIS_BITMAP    = 0x0004; // Item displays a bitmap

// Constants for Menu Item Attributes (MIA_*) - Illustrative
// These values are common in Windows resource definitions.
constexpr quint16 MIA_ENABLED  = 0x0000; // Item is enabled (default)
constexpr quint16 MIA_GRAYED   = 0x0001; // Item is grayed (disabled visually)
constexpr quint16 MIA_DISABLED = 0x0002; // Item is disabled (cannot be selected)
constexpr quint16 MIA_CHECKED  = 0x0008; // Item has a checkmark

constexpr quint16 KC_VIRTUALKEY = 0x0001;
constexpr quint16 KC_SHIFT      = 0x0008;
constexpr quint16 KC_CTRL       = 0x0010;
constexpr quint16 KC_ALT        = 0x0020;

quint16 peekUInt16(const QByteArray& data, qsizetype offset)
{
    const auto* bytes = reinterpret_cast<const uchar*>(data.constData() + offset);
    return quint16(bytes[0]) | (quint16(bytes[1]) << 8);
}


quint32 peekUInt32(const QByteArray& data, qsizetype offset)
{
    const auto* bytes = reinterpret_cast<const uchar*>(data.constData() + offset);
    return quint32(bytes[0]) | (quint32(bytes[1]) << 8) |
           (quint32(bytes[2]) << 16) | (quint32(bytes[3]) << 24);
}

bool parseNativeMenuBlock(const QByteArray& data, qsizetype& offset, QString& output,
                          int indentLevel, bool isSubMenu)
{
    const qsizetype blockStart = offset;
    if (offset + 10 > data.size())
        return false;

    const quint32 blockSize = peekUInt32(data, offset);
    if (blockSize < 10 || blockSize > quint32(data.size() - blockStart))
        return false;
    offset += 4;

    quint16 cp = peekUInt16(data, offset); offset += 2;
    if (cp == 0) cp = 850;
    const quint16 dataOffset = peekUInt16(data, offset); offset += 2;
    const quint16 count = peekUInt16(data, offset); offset += 2;
    if (dataOffset != 4 || count > 1000)
        return false;

    const qsizetype blockEnd = blockStart + qsizetype(blockSize);
    const QString indent(indentLevel * 4, QChar(u' '));
    output += isSubMenu ? indent + QStringLiteral("{\n")
                        : QStringLiteral("MENU\n") + indent + QStringLiteral("{\n");

    for (quint16 i = 0; i < count; ++i) {
        if (offset + 6 > blockEnd)
            return false;

        const quint16 style = peekUInt16(data, offset); offset += 2;
        const quint16 attrib = peekUInt16(data, offset); offset += 2;
        const quint16 id = peekUInt16(data, offset); offset += 2;
        const QString itemIndent((indentLevel + 1) * 4, QChar(u' '));

        if ((style & MIS_SUBMENU) != 0) {
            const QString popupText = RT_STRING::ReadNullTerminatedString(data, offset, cp);
            if (offset > blockEnd)
                return false;
            output += itemIndent + QStringLiteral("POPUP \"") + popupText + QStringLiteral("\"\n");
            if (!parseNativeMenuBlock(data, offset, output, indentLevel + 1, true))
                return false;
        } else if ((style & MIS_SEPARATOR) != 0 || id == 0xFFFF) {
            output += itemIndent + QStringLiteral("MENUITEM SEPARATOR\n");
        } else if ((style & MIS_BITMAP) != 0) {
            // Native OS/2/LX menu templates store the bitmap command/resource ID
            // directly in the item header. There is no trailing bitmap descriptor.
            output += itemIndent + QStringLiteral("MENUITEM \"\", ") + QString::number(id) +
                      QStringLiteral(", MIS_BITMAP");
            if ((attrib & MIA_GRAYED) != 0) output += QStringLiteral(", GRAYED");
            if ((attrib & MIA_DISABLED) != 0) output += QStringLiteral(", DISABLED");
            if ((attrib & MIA_CHECKED) != 0) output += QStringLiteral(", CHECKED");
            output += QChar(u'\n');
        } else {
            const QString itemText = RT_STRING::ReadNullTerminatedString(data, offset, cp);
            if (offset > blockEnd)
                return false;
            output += itemIndent + QStringLiteral("MENUITEM \"") + itemText +
                      QStringLiteral("\", ") + QString::number(id);
            if ((attrib & MIA_GRAYED) != 0) output += QStringLiteral(", GRAYED");
            if ((attrib & MIA_DISABLED) != 0) output += QStringLiteral(", DISABLED");
            if ((attrib & MIA_CHECKED) != 0) output += QStringLiteral(", CHECKED");
            output += QChar(u'\n');
        }
    }

    if (offset > blockEnd)
        return false;
    offset = blockEnd;
    output += indent + QStringLiteral("}\n");
    return true;
}

} // namespace

quint8 OS2_RT_MENU::ReadByte(const QByteArray& data, qsizetype& offset)
{
    if (offset + 1 > data.size())
        throw std::runtime_error("Attempted to read past end of data.");
    return static_cast<quint8>(data.at(offset++));
}

quint16 OS2_RT_MENU::ReadUInt16(const QByteArray& data, qsizetype& offset)
{
    if (offset + 2 > data.size())
        throw std::runtime_error("Attempted to read past end of data for ushort.");
    const quint16 value = peekUInt16(data, offset);
    offset += 2;
    return value;
}

void OS2_RT_MENU::ParseMenu(const QByteArray& data, qsizetype& offset, QString& output,
                            int indentLevel, bool isSubMenu)
{
    const QString indent(indentLevel * 4, QChar(u' '));

    // Menu Header fields
    const quint16 db = ReadUInt16(data, offset);    // 16 1 db
    const quint16 type = ReadUInt16(data, offset);  // 16 1 type (0 or 1)
    quint16 cp = ReadUInt16(data, offset);          // 16 1 cp (codepage, e.g., 850)
    if (cp == 0) cp = 850;                     // OS/2 1.x default / absent codepage
    const quint16 offs = ReadUInt16(data, offset);  // 16 1 offs (starting offset of menu data from start of structure)
    const quint16 count = ReadUInt16(data, offset); // 16 1 count (number of items)
    Q_UNUSED(db)
    Q_UNUSED(offs)

    // If the menu type is 1, count is followed by another 16-bit field, ppoffs.
    // As per the prompt, we won't handle type 1 menus fully, so we just consume the ppoffs field.
    if (type == 1)
        ReadUInt16(data, offset); // ppoffs (presentation parameter offset)

    // Emit the RC file syntax for the menu or popup block
    if (isSubMenu) {
        // For submenus, the 'POPUP "Text"' part is handled by the parent item.
        output += indent + QStringLiteral("{\n");
    } else {
        output += QStringLiteral("MENU\n");
        output += indent + QStringLiteral("{\n");
    }

    // Parse each menu item
    for (quint16 i = 0; i < count; ++i) {
        const QString itemIndent((indentLevel + 1) * 4, QChar(u' '));
        const quint16 style = ReadUInt16(data, offset);  // 16 1 style (MIS_*)
        const quint16 attrib = ReadUInt16(data, offset); // 16 1 attrib (MIA_*)
        const quint16 id = ReadUInt16(data, offset);     // 16 1 Id (item identifier)

        // Handle optional data based on the item's style
        if ((style & MIS_SUBMENU) != 0) {
            // Data is a menu structure, read the submenu's text first
            const QString popupText = RT_STRING::ReadNullTerminatedString(data, offset, cp);
            output += itemIndent + QStringLiteral("POPUP \"") + popupText + QStringLiteral("\"\n");
            // Recursively call ParseMenu for the submenu's content
            ParseMenu(data, offset, output, indentLevel + 1, true);
        } else if ((style & MIS_SEPARATOR) != 0 || id == 65535) {
            output += itemIndent + QStringLiteral("MENUITEM SEPARATOR\n");
        } else if ((style & MIS_BITMAP) != 0) {
            const quint8 bitmapType = ReadByte(data, offset);
            QString bitmapId;
            if (bitmapType == 0xFF) {
                const quint16 resourceId = ReadUInt16(data, offset);
                bitmapId = QString::number(resourceId);
            } else if (bitmapType == 0x00) {
                bitmapId = QStringLiteral("0");
            } else if (bitmapType == '#') {
                const qsizetype start = offset;
                while (offset < data.size() && data.at(offset) >= '0' && data.at(offset) <= '9')
                    ++offset;
                bitmapId = offset > start
                    ? QString::fromLatin1(data.constData() + start, int(offset - start))
                    : QStringLiteral("INVALID_BITMAP_ID");
            } else {
                bitmapId = QStringLiteral("UNKNOWN_BITMAP_FORMAT");
            }

            output += itemIndent + QStringLiteral("MENUITEM \"\", ") + QString::number(id) +
                      QStringLiteral(", MIS_BITMAP");
            if (!bitmapId.isEmpty() && bitmapId != QStringLiteral("0"))
                output += QStringLiteral(", ") + bitmapId;
            if ((attrib & MIA_GRAYED) != 0) output += QStringLiteral(", GRAYED");
            if ((attrib & MIA_DISABLED) != 0) output += QStringLiteral(", DISABLED");
            if ((attrib & MIA_CHECKED) != 0) output += QStringLiteral(", CHECKED");
            output += QChar(u'\n');
        } else {
            // Data is a null-terminated string for the menu item text
            const QString itemText = RT_STRING::ReadNullTerminatedString(data, offset, cp);
            output += itemIndent + QStringLiteral("MENUITEM \"") + itemText +
                      QStringLiteral("\", ") + QString::number(id);
            if ((attrib & MIA_GRAYED) != 0) output += QStringLiteral(", GRAYED");
            if ((attrib & MIA_DISABLED) != 0) output += QStringLiteral(", DISABLED");
            if ((attrib & MIA_CHECKED) != 0) output += QStringLiteral(", CHECKED");
            output += QChar(u'\n');
        }
    }
    output += indent + QStringLiteral("}\n"); // End of current menu/popup block
}

QString OS2_RT_MENU::Get(const QByteArray& data, const ResourceEntry& entry)
{
    if (data.isEmpty())
        return QStringLiteral("// Error: Input data is null or empty.");

    // --- Native OS/2/LX menu template: 32-bit block size, codepage,
    //     data offset, item count. Keep the legacy parser below as fallback.
    try {
        if (data.size() >= 10) {
            QString output;
            qsizetype nativeOffset = 0;
            if (parseNativeMenuBlock(data, nativeOffset, output, 0, false) &&
                nativeOffset == data.size())
                return output;
        }
    } catch (const std::exception&) {
        // Continue with the legacy parser used by already-tested resources.
    }

    // --- Attempt to parse as a legacy Menu resource ---
    try {
        if (data.size() >= 10) {
            const quint16 type = peekUInt16(data, 2);
            const quint16 offs = peekUInt16(data, 6);
            const quint16 count = peekUInt16(data, 8);

            if ((type == 0 || type == 1) && offs < data.size() && count < 1000) {
                QString output;
                qsizetype menuOffset = 0;
                ParseMenu(data, menuOffset, output, 0);
                return output;
            }
        }
    } catch (const std::exception&) {
        // This indicates that the data was too short or malformed for a menu.
        // Continue to try other types.
    }

    // --- Attempt to parse as a StringTable resource ---
    try {
        if (data.size() >= 3)
            return RT_STRING::Get(data, entry.format, entry.isOs2, entry.baseId);
    } catch (const std::exception&) {
        // Continue to try other types.
    }

    // --- Attempt to parse as an AccelTable resource ---
    try {
        if (data.size() >= 6) {
            const quint16 count = peekUInt16(data, 0);
            const quint16 type1 = peekUInt16(data, 4);
            if (count < 1000 && (type1 == 0 ||
                (type1 & (KC_VIRTUALKEY | KC_SHIFT | KC_CTRL | KC_ALT)) != 0))
            {
                return RT_ACCELTABLE::Get(data, entry.format);
            }
        }
    } catch (const std::exception&) {
        // Continue to the final error.
    }

    return QStringLiteral("// Error: Could not determine resource type or parse data.");
}

} // namespace resources
} // namespace peare
