using System;

namespace Peare
{
    [Flags]
    public enum LE_OBJECT_FLAGS : uint
    {
        LE_OBJECT_FLAG_READABLE = 1,
        LE_OBJECT_FLAG_WRITABLE = 2,
        LE_OBJECT_FLAG_EXECUTABLE = 4,
        LE_OBJECT_FLAG_RESOURCE = 8,
        LE_OBJECT_FLAG_DISCARABLE = 16,
        LE_OBJECT_FLAG_SHARED = 32,
        LE_OBJECT_FLAG_CONTAINS_PRELOAD_PAGES = 64,
        LE_OBJECT_FLAG_CONTAINS_INVALID_PAGES = 128,
        LE_OBJECT_FLAG_CONTAINS_ZEROFILL_PAGES = 256,
        LE_OBJECT_FLAG_RESIDENT = 512,
        LE_OBJECT_FLAG_RESIDENT_AND_CONTIGUOUS = 768,
        LE_OBJECT_FLAG_RESIDENT_AND_LONG_LOCKABLE = 1024,
        LE_OBJECT_FLAG_16_16_ALIAS_REQUIRED = 4096,
        LE_OBJECT_FLAG_BIG_DEFAULT_BIT_SETTING = 8192,
        LE_OBJECT_FLAG_CONFORMING_FOR_CODE = 16384,
        LE_OBJECT_FLAG_IO_PRIVILEGE_LEVEL = 32768
    }
}
